version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
        POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB_USERNAME=${POSTGRES_DB_USERNAME}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
    env_file:
      - .env