# Reference:
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: PyPI-Publish

on:
  workflow_dispatch:
  push:
    branches:
      - pypi_releases

jobs:
    build-python-package:

        name: Build Python Package
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.x"
            
            - name: Install pypa/build
              run: >-
                python3 -m
                pip install
                build
                --user
            
            - name: Build a binary wheel and a source tarball
              run: python3 -m build
            
            - name: Store the distribution packages
              uses: actions/upload-artifact@v3
              with:
                name: python-package-distributions
                path: dist/
    
    publish-to-pypi:
      name: Publish Python Distribution To PyPI
      needs:
        - build-python-package
      runs-on: ubuntu-latest
      environment:
        name: testpypi
        url: https://test.pypi.org/p/plum-project
      permissions:
        id-token: write
      
      steps:
        - name: Download all the dists
          uses: actions/download-artifact@v3
          with:
            name: python-package-distributions
            path: dist/
        - name: Publish distribution to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
              repository-url: https://test.pypi.org/legacy/